export const copy = {
  appName: "Proof",
  appSummary: "내일의 계획과 오늘의 확인을 짧게 이어갑니다.",
  onboardingTitle: "하고 싶은 것과 무너지는 장면을 선명하게 봅니다.",
  onboardingDescription: "처음 세 가지를 바탕으로 구체 질문을 만들고, 답변을 행동 강령으로 압축합니다.",
  habitLabel: "만들고 싶은 습관",
  habitPlaceholder: "예: 주 3회 토익 공부",
  breakdownContextLabel: "보통 무너지는 시간대나 상황",
  breakdownBehaviorLabel: "그때 주로 하는 행동",
  breakdownBehaviorPlaceholder: "예: 숏폼 보다가 시간 다 씀",
  eveningTitle: "오늘을 확인하고 내일을 정합니다.",
  planTitle: "내일은 언제, 어디서, 무엇을 해볼까요?",
  planPlaceholder: "예: 저녁 8시, 책상에서, 토익 RC 10문제",
  minimumPlanLabel: "최소 버전",
  minimumPlanPlaceholder: "예: RC 3문제만",
  checkInTitle: "계획한 걸 해보셨나요?",
  contextQuestion: "그 순간 뭘 하고 있었어요?",
  contextPlaceholder: "예: 침대에서 숏폼을 보고 있었어요",
  missedPlan: "아직 계획이 없어요. 한 줄만 정해볼까요?",
  recordTitle: "지금까지의 기록",
  settingsTitle: "알림 설정",
  emptyRecord: "기록이 쌓이면 여기에 보입니다.",
  patternLead: "최근 기록에서는",
  patternTail: "이 자주 보여요. 오늘은 그 시간대를 어떻게 다르게 보낼까요?",
  coachQuestionsButton: "구체 질문 만들기",
  coachSynthesisButton: "행동 강령 만들기",
};

export const resultLabels = {
  done: "했어요",
  partial: "일부만 했어요",
  not_done: "하지 않았어요",
  no_response: "응답 없음",
};
